### ISSUE TITLE
安装完所需库后 执行ui.py报错

### ISSUE THREAD

**Issue by yinqimin** [cuifengcn/TAICHI-flet#23]
flet用的0.4.0版本
python3.9 ./ui.py
LSOpenURLsWithRole() failed with error -10825 for the file /Users/min/.flet/bin/flet-0.4.0/Flet.app.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 917, in run
![image](https://user-images.githubusercontent.com/16587899/219873216-fa671f24-e58b-4ca0-a6b1-3f0c6e6b7174.png)

**Comment by cuifengcn** [comment]
有更多报错信息吗，看不出来
