### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' (D:\Program Files (x86)\太极\PIL\__init__.pyc)

### ISSUE THREAD

**Issue by li589** [cuifengcn/TAICHI-flet#73]
<img width="290" alt="{B1ACD615-878B-4E44-AB11-750ECBE2E619}" src="https://github.com/user-attachments/assets/bad8b13b-5e6f-4375-8f47-3daa9dccf857">
问题如上，在启动太极时，本人是VIP永久会员，开始使用正常，重启电脑后就不正常了，具体代码如下：
Traceback (most recent call last):
  File "ui.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils.py", line 60, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "statics.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "PIL\Image.py", line 100, in <module>
ImportError: cannot import name '_imaging' from 'PIL' (D:\Program Files (x86)\太极\PIL\__init__.pyc)

**Comment by cuifengcn** [comment]
很可能是杀毒软件或win安全中心将某些文件隔离了，重装或添加客服wx进行解决噢

**Comment by cuifengcn** [comment]
wx_wanld

**Comment by li589** [comment]
问题已经解决，确实是360误杀了
